

'''
Values derived from https://www.mdpi.com/2079-9292/8/9/943
'''
MAX_LONG_ACC_NORMAL = 1.47
MAX_LONG_ACC_AGGR = 3.5
MAX_LONG_ACC_EMG = 5

MAX_LAT_ACC_NORMAL = 4
MAX_LAT_ACC_AGGR = 5.6
MAX_LAT_ACC_EMG = 7.6

MAX_LONG_DEC_NORMAL = -2
MAX_LONG_DEC_AGGR = -3.5
MAX_LONG_DEC_EMG = -5

MAX_LAT_DEC_NORMAL = -4
MAX_LAT_DEC_AGGR = -5.6
MAX_LAT_DEC_EMG = -7.6

MAX_ACC_JERK_NORMAL = 0.9
MAX_ACC_JERK_AGGR = 2

MAX_DEC_JERK_NORMAL = -0.9
MAX_DEC_JERK_AGGR = -2

STOP_LOC_STD_DEV = 1.5
STOP_VEL_TOLERANCE = 0.5

PROCEED_VEL_MEAN = 8
PROCEED_VEL_SD = 1

MAINTAIN_VEL_SD = 2
TARGET_VEL = 14

PROCEED_ACC_SD = 0.5
PROCEED_ACC_MEAN = 1

STOP_DEC_STD_DEV = 0.01

STOP_YAW_TOLERANCE = 0.08
PROCEED_YAW_TOLERANCE = 0.15

CAR_LENGTH = 5
CAR_WIDTH = 2

N_STOP_POS_SAMPLES = {'prep-turn_s':5}
N_STOP_VEL_SAMPLES = {'prep-turn_s':5}

CAR_FOLLOWING_SAFETY_DISTANCE = 2

N_PROCEED_POS_SAMPLES = {'prep-turn_s':5,'int-entry_n':10}
N_PROCEED_VEL_SAMPLES = {'prep-turn_s':5,'int-entry_n':100}

EXIT_SEGMENTS = {'prep-turn_s':'exec-turn_s','int-entry_n':'l_n_s_l'}

LATERAL_TOLERANCE_STOPLINE = [1,0.5,-0.5,-1]
LATERAL_TOLERANCE_EXITLINE = [1,0.5,-0.5,-1]

LANE_BOUNDARY = {'prep-turn_s|proceed':'l_s_n|left_boundary'}

ACTION_MAP = {'prep-turn_':['wait','go']}
LP_FREQ = 0.1


